name: Keep Render Backend Awake

on:
  schedule:
    - cron: '*/7 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -s https://the-project-hj0y.onrender.com/api/jobs > /dev/null
